config/routes.rb
Conduct::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :votes
      resources :topics do
        resources :ideas
      end
    end
  end

  get "password_resets/new"
  resources :votes

  resources :sessions
  resources :users

  resources :topics do
    resources :ideas
  end

  resources :password_resets
  resources :access_token
  
  get 'forgot', to: 'password_resets#new'

  get 'account/edit', to: 'users#edit'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  get 'api', to: 'static#api'

  root 'static#landing'

end

app/models/idea.rb
class Idea < ActiveRecord::Base

  has_many :votes
  belongs_to :topic, foreign_key: "secret"

  def self.qty_on(date)
    where("date(created_at) = ?",date).count
  end
  
end

app/controllers/api/v1/ideas_controller.rb
module Api
  module V1
    class IdeasController < ApplicationController

      respond_to :json
      
      before_filter :set_topic
      before_action :set_idea, only: [:show, :edit, :update, :destroy]

      before_filter :validate_access_token

      def index
        @ideas = @topic.ideas.order("#{sort_field} #{sort_dir}")
        render 'ideas/index'
      end

      def show
        render 'ideas/show'
      end

      def create
        @idea = Idea.new(idea_params)
        @idea.user_id = @user.id
        @idea.topic_id = @topic.secret
        @idea.save
        render 'ideas/show', status: :created, location: [@topic, @idea]
      end

      def update
        @idea.update(idea_params)
        render 'ideas/show', status: :ok, location: [@topic, @idea]
      end

      def destroy
        @idea.destroy
        render nothing: true, :status => :no_content
      end

      private

      def sort_field
        %w{id title created_at}.include?(params[:sort_field]) ? params[:sort_field] : 'created_at'
      end

      def sort_dir
        %w{asc desc}.include?(params[:sort_dir]) ? params[:sort_dir] : 'desc'
      end

      def validate_access_token
        @user = User.find_by_access_token(request.headers["X-API-Key"])
        unless @user
          render nothing: true, :status => :unauthorized
        end
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_topic
        @topic = Topic.find_by_secret(params[:topic_id])
        unless @topic
          render nothing: true, :status => :not_found
        end
      end

      def set_idea
        begin
        @idea = @topic.ideas.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          render nothing: true, :status => :not_found
        end
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def idea_params
        params.require(:idea).permit(:title, :description)
      end
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :set_topic, only: [:show, :create]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user_id = current_user.id
    @idea.topic_id = @topic.to_param
    
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @topic, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@topic, @idea] }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @topic, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  private
    
    def set_topic
      if params["topic_id"]
        @topic = Topic.find_by_secret(params["topic_id"])
      else
        @topic = Topic.find_by_secret(@idea.topic_id)
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :description, :topic_id, :user_id)
    end
end

app/views/ideas/_form.html.erb
<div class="form-centered">

  <h1>Edit idea</h1>

  <%= form_for([@topic, @idea]) do |f| %>
    <% if @idea.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

        <ul>
        <% @idea.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.submit "Save changes" %>
    </div>
  <% end %>
</div>

app/views/ideas/edit.html.erb
<%= render 'form' %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Topic</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.description %></td>
        <td><%= idea.topic_id %></td>
        <td><%= idea.user_id %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @idea.topic_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea.user_id %>
</p>