config/routes.rb
Conduct::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :votes
      resources :topics do
        resources :ideas
      end
    end
  end

  get "password_resets/new"
  resources :votes

  resources :sessions
  resources :users

  resources :topics do
    resources :ideas
  end

  resources :password_resets
  resources :access_token
  
  get 'forgot', to: 'password_resets#new'

  get 'account/edit', to: 'users#edit'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  get 'api', to: 'static#api'

  root 'static#landing'

end

app/models/topic.rb
include ApplicationHelper

class Topic < ActiveRecord::Base

  belongs_to :user

  has_many :ideas, :primary_key => "secret"
  after_create :generate_secret

  def to_param
    secret
  end
  
  private

  def generate_secret
    begin
      self[:secret] = generate_token(6)
    end while Topic.exists?(:secret => self[:secret])
    save!
  end

end

app/controllers/api/v1/topics_controller.rb
module Api
  module V1
    class TopicsController < ApplicationController

      respond_to :json
      before_action :set_topic, only: [:show, :edit, :update, :destroy]

      before_filter :authenticate, except: [:create]

      before_filter :check_per_page_is_an_integer, only: [:index]
      before_filter :check_per_page_is_in_range, only: [:index]

      def index
        @topics = @user.topics.order("#{sort_field} #{sort_dir}").paginate(:page => params[:page], :per_page => params[:per_page])
        render 'topics/index'
      end

      def show
        render 'topics/show'
      end

      def create
        @topic = Topic.new(topic_params)
        @topic.user_id = @user.id if @user
        @topic.save
        render 'topics/show', status: :created, location: @topic
      end

      def update
        @topic.update(topic_params)
        render 'topics/show', status: :ok, location: @topic
      end

      def destroy
        @topic.destroy
        render nothing: true, status: :no_content
      end

      private

      def sort_field
        %w{id title created_at}.include?(params[:sort_field]) ? params[:sort_field] : 'created_at'
      end

      def sort_dir
        %w{asc desc}.include?(params[:sort_dir]) ? params[:sort_dir] : 'desc'
      end

      def authenticate
        @user = current_user

        unless @user
          render nothing: true, status: :unauthorized
        end
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_topic
        @topic = Topic.find_by_secret(params[:id])
        unless @topic
          render nothing: true, status: :not_found
        end
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def topic_params
        params.require(:topic).permit(:title, :description, :locked, :user_id)
      end

      def check_per_page_is_an_integer
        unless params["per_page"].nil?
          unless params["per_page"].is_i?
            render text: "Parameter per_page is not an integer", status: :bad_request
          end
        end
      end

      def check_per_page_is_in_range
        per_page = params["per_page"] || 20
        per_page = per_page.to_i

        Rails.logger.debug "per_page = #{per_page}"
        Rails.logger.debug "per_page in range = #{per_page.between?(1, 10000)}"

        unless per_page.between?(1, 10000)
          Rails.logger.debug "Throw a 400"
          render text: "Parameter per_page is out of range", status: :bad_request
        end
      end

    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter :authenticate
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.where({user_id: current_user.id})
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
  
  def authenticate
    redirect_to(login_path) unless !current_user.nil?
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find_by_secret(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:title, :description, :locked, :user_id)
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <div class="text-centered">
      <div switch class="switch" ng-class="state" data-state="<%= @topic.locked %>">
        <div class="switch--toggle">
          <span
            ng-class="{
              'active': !on
            }"
          >
            Unlocked
          </span>
          <span
            ng-class="{
              'active': on
            }"
          >
            Locked
          </span>
        </div>

        <div class="field hide">
          <%= f.check_box :locked, data: { "ng-model" => "on" } %>
        </div>

      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit button_text %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="form-centered">
  <h1>Edit Topic</h1>
  <%= render :partial => 'form', :locals => {:button_text => "Save Changes"} %>
</div>

app/views/topics/index.html.erb
<% if @topics.empty? %>

  <div class="text-centered">
    <h1 class="text-spacious">It looks like you don't have any topics yet</h1>
  </div>
    
  <div class="container">
    <%= render 'static/landing/hero' %>
  </div>
  
<% else %>

  <h1>My topics</h1>
  <p><small>Signed in as <%= current_user.email %> <%= link_to "Log out", logout_path %></small></p>

  <ul class="topics">
    <% @topics.each do |topic| %>
      <li id="topic-<%= topic.id %>">      
        <div class="topic-body">
          <h2><%= link_to topic.title, "/topics/#{topic.secret}" %></h2>
          <p><%= topic.description %></p>
          <p class="meta">Created by you <%= time_ago_in_words(topic.created_at) %> ago | <%= link_to 'Edit', edit_topic_path(topic) %> | <%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <ul class="topic-stats list-unstyled">
            <li class="stats-ideas"><%= pluralize(topic.ideas.count, 'idea') %></li>
            <li class="stats-ideas"><%=  pluralize(topic.ideas.map(&:user_id).uniq.count, 'contributor') %></li>
            <li class="stats-ideas"><%= pluralize(0, 'vote') %>
          </ul>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/topics/new.html.erb
<div class="form-centered">
  <h1>New Topic</h1>
  <%= render :partial => 'form', :locals => {:button_text => "Create Topic"} %>
</div>

app/views/topics/show.html.erb
<header class="page-header">
  <h1><%= @topic.title %></h1>
  <p><%= @topic.description %></p>
  <p class="meta">Created 20th June 2013 by adambutler | Share link is - <%= "#{request.protocol}#{request.host}/topics/#{@topic.secret}" %></p>
  <div class="labels">
    <span class="label label-<%= @topic.locked ? 'error' : 'success' %>"><%= @topic.locked ? 'closed' : 'open' %></span>  

    <%= link_to 'Settings', edit_topic_path(@topic), :class => "label" %>

  </div>
</header>

<div class="row-fluid" ng-controller="TopicController" ng-init="construct({}, '<%= @topic.secret %>')">

  <div class="column-right">

    <ul class="sidebar list-unstyled">

      <li class="sidebar-item-chart">
        <h3 class="icon-title"><i class="icon icon-mini_gauge"></i>Ideas in the last 7 days</h3>
        <canvas id="canvas" height="150" width="315"></canvas>
      </li>

      <% unless @topic.locked %>

        <li class="sidebar-item-new-idea">
          <h3 class="icon-title"><i class="icon icon-mini_pencil"></i>Suggest an idea</h3>

          <% if current_user %>
            <form name="new" ng-submit="addIdea()">

              <div class="field">
                <label for="idea_name">Name</label><br>
                <input type="text" ng-model="newIdea.title" required>
              </div>
              <div class="field">
                <label for="idea_description">Description</label><br>
                <textarea type="text" ng-model="newIdea.description"></textarea>
              </div>
              <div class="actions">
                <input type="submit" value="Create Idea" ng-disabled="new.$invalid">
              </div>

            </form>
          <% else %>
            <div class="text-centered text-spacious">
              <a href="/login" class="link-subtle">Log in to suggest an idea</a>
            </div>

          <% end %>

        </li>

      <% end %>

    </ul>
  </div>

  <div class="column-left">
    <div class="column-content">

      <div class="text-centered text-spacious" ng-show="topic.ideas.length == 0">
        <div class="icon-container">
          <div class="icon icon-battery"></div>
        </div>
        <h2>This topic hasn't got any suggestions yet.</h2>
        <p>Why not be the first to add a suggestion</p>
      </div>

      <form class="action-bar" ng-hide="topic.ideas.length == 0">
        <label for="sort">Sort by - </label>
        <select ng-model="sort">
          <option value="-votes.total_vote_qty">Votes - Decending</option>
          <option value="votes.total_vote_qty">Votes - Accending</option>
          <option value="-created_at">Created - Newest First</option>
          <option value="created_at">Created - Oldest First</option>
          <option value="title">Title - Accending</option>
          <option value="-title">Title - Decending</option>
        </select>
      </form>

      <% if @topic.locked %>
        <p class="flash flash-alert"><%= @owner ? 'You have' : 'The owner has' %> closed this topic, you can not vote or add new ideas.</p>
      <% end %>

      <ul class="suggestions list-unstyled" ng-hide="topic.ideas.length == 0">

        <li ng-repeat="idea in topic.ideas | orderBy: sort">
          <div class="votebox votebox-<%= @topic.locked ? 'error' : 'success' %>">
            <span class="score">{{idea.votes.total_vote_qty}}</span>
            <span ng-disabled="votable(idea)" class="vote" ng-click="vote(idea)"
              ng-class="{
                'vote-voted': !votable(idea)
              }"
            >
              {{votable(idea) && 'vote' || '✔'}}
            </span>
          </div>
          <div class="idea-body">
            <h2>{{idea.title}}</h2>
            <p>{{idea.description}}</p>
            <p class="meta">Suggested by #{{idea.user_id}} {{idea.created_time_ago_in_words}}
              <span ng-show="idea.owner">
                | <a href="{{idea.edit_url}}">edit</a>
                | <a href="{{idea.public_link}}/edit">delete</a>
              </span>
            </p>
          </div>
        </li>

      </ul>
    </div>
  </div>
</div>

<script type="text/javascript">
  var lineChartData, myLine;

  lineChartData = {
    labels: <%= raw ((1.week.ago.to_date..Date.today).map{ |date| date.strftime("%b %d") }) %>,
    datasets: [
      {
        fillColor: "rgba(242,155,44,1)",
        strokeColor: "rgba(242,155,44,0)",
        data: <%= (1.week.ago.to_date..Date.today).map { |date| @topic.ideas.qty_on(date).to_f}.inspect %>
      }
    ]
  };

  myLine = new Chart(document.getElementById("canvas").getContext("2d")).Line(lineChartData, {
    pointDot : false,
    scaleShowGridLines: false,
    scaleFontFamily : "'UbuntuRegular'",
    scaleFontColor : "#b2bcc5",
    scaleFontSize : 11,
  });
</script>