config/routes.rb
Conduct::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :votes
      resources :topics do
        resources :ideas
      end
    end
  end

  get "password_resets/new"
  resources :votes

  resources :sessions
  resources :users

  resources :topics do
    resources :ideas
  end

  resources :password_resets
  resources :access_token
  
  get 'forgot', to: 'password_resets#new'

  get 'account/edit', to: 'users#edit'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  get 'api', to: 'static#api'

  root 'static#landing'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/api/v1/votes_controller.rb
module Api
  module V1
    class VotesController < ApplicationController

      respond_to :json
      before_action :set_vote, only: [:show, :edit, :update, :destroy]

      # GET /votes
      # GET /votes.json
      def index
        @votes = Vote.all
      end

      # GET /votes/1
      # GET /votes/1.json
      def show
      end

      # GET /votes/new
      def new
        @vote = Vote.new
      end

      # GET /votes/1/edit
      def edit
      end

      # POST /votes
      # POST /votes.json
      def create
        @vote = Vote.new(vote_params)
        @vote.user_id = current_user.id

        respond_to do |format|
          if @vote.save
            format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
            format.json { render action: 'show', status: :created, location: @vote }
          else
            format.html { render action: 'new' }
            format.json { render json: @vote.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /votes/1
      # PATCH/PUT /votes/1.json
      def update
        respond_to do |format|
          if @vote.update(vote_params)
            format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @vote.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /votes/1
      # DELETE /votes/1.json
      def destroy
        @vote.destroy
        respond_to do |format|
          format.html { redirect_to votes_url }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_vote
          @vote = Vote.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def vote_params
          params.require(:vote).permit(:idea_id, :user_id)
        end
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)
    @vote.user_id = current_user.id

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vote }
      else
        format.html { render action: 'new' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:idea_id, :user_id)
    end
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idea_id %><br>
    <%= f.number_field :idea_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <thead>
    <tr>
      <th>Idea</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.idea_id %></td>
        <td><%= vote.user_id %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idea:</strong>
  <%= @vote.idea_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @vote.user_id %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>