config/routes.rb
Conduct::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :votes
      resources :topics do
        resources :ideas
      end
    end
  end

  get "password_resets/new"
  resources :votes

  resources :sessions
  resources :users

  resources :topics do
    resources :ideas
  end

  resources :password_resets
  resources :access_token
  
  get 'forgot', to: 'password_resets#new'

  get 'account/edit', to: 'users#edit'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  get 'api', to: 'static#api'

  root 'static#landing'

end

app/views/layouts/_footer.html.erb
<footer class="main">
  <p>Made with love in Bristol by <a href="http://lab.io">Adam Butler</a> with a little help from some friends</h4>
  <p><small>&copy; <%= Time.now.year %> Adam Butler</small></small<>
</footer>

app/views/layouts/_header.html.erb
<header class="main">
  <a href="/"><h1>Conduct.io <small>Group decisions made easy</small></h1></a>
  <% if request.env['PATH_INFO'] != '/' %>
    <nav>
      <%= link_to_unless_current('My Topics', topics_path) { |link| raw "<span class=\"current\">#{link}</span>"} %>
      <%= link_to_unless_current('New Topic', new_topic_path) { |link| raw "<span class=\"current\">#{link}</span>"} %>
    </nav>
    <div class="user">
      <a href="#">
        <% if current_user %>
          <%= gravatar_image_tag(current_user.email, :class => 'avatar small') %>
        <% else %>
          <%= image_tag("user.png", :class => 'avatar small') %>
        <% end %>
      </a>
      <ul class="dropdown">
        <li><%= link_to "edit profile", '#' %></li>
        <li><%= link_to "logout", logout_path %></li>
      </ul>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Conduct" class="<%= get_theme %> <%= "page-#{params[:controller]}-#{params[:action]}" %>">
  <head>
    <title>Conduct</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <div id="root">
      <%= render 'layouts/header' %>

      <div class="body">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= yield %>
      </div>

      <div id="root-footer"></div>
    </div>
    <%= render 'layouts/footer' %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-56297105-1', 'auto');
      ga('send', 'pageview');

    </script>

  </body>
</html>